# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'b512c64a03e46f8a5c5d860f95fb457d'
  config.secret_key = '69d51e645d3445726c2cd2bac84a6257'
  config.default_from = 'myriam.delbreil@live.fr'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
